### PR TITLE
Support for multitag requests on ENIP

### PR DESCRIPTION
**Pull request by afmurillo**
Two functions are added to devices.py and protocols.py to support sending and receiving multiple tags using ENIP.

### CODE REVIEW

**Review by noleti — DISMISSED** [review]
Looks good to me, overall few additions, minor cleanup of prior stuff

**Comment by noleti** [comment]
Thanks @afmurillo, but it looks like you added some debug `--print` and `print()` into that last patch. Could you please remove those again and push another commit?

**Comment by afmurillo** [comment]
Hello, @noleti  I have commented the print() status. The --print present in lines 472 and 513 was the result of the debug session we had a couple of weeks ago. Those --print allow DHALSIM PLCs to receive tags values using ENIP.

**Review by noleti — APPROVED** [review]
all good per shared discussion

**Pull request merged**
