### PR TITLE
Devs contribute

### PR DESCRIPTION
**Pull request by francozappa**
Checks:

* [x] User installation commands
* [x] Developer installation commands
* [x] Clear how to test/modify/add a new `Protocol` or `State`

### CODE REVIEW

**Comment by remmihsorp** [comment]
### Current Read The Docs
- [ ] Missing Info for installing rednose (```pip install rednose```)
- [ ] Missing info for installing pymodbus (```pip install -U pymodbus```) 
### User Installation
- [ ] missing python-pip installation info
- [ ] not sure how to test
### Dev Installation
- [ ] missing python-pip installation info
- [ ] nosetest command not found // installed python-nose
- [ ] no module networkx // installed python-networkx

**Comment by francozappa** [comment]
Hi @remmihsorp,

In general I think that we do not have to provide instructions about `pip` installation.

* [ ] test user installation with `requirements.txt`
* [ ] test dev installation with `requirements-dev.txt`

Thanks a lot for the review.

**Comment by francozappa** [comment]
Hi @remmihsorp,

In general I think that we do not have to provide instructions about `pip` installation.

* [ ] test user installation with `requirements.txt`
* [ ] test dev installation with `requirements-dev.txt`

Thanks a lot for the review.

**Comment by remmihsorp** [comment]
Hi @francozappa,

;; minicps user

- [ ] downloading example and running `sudo python run.py` halts with missing nose.
- [ ] `pip install -r requirements.txt` runs `examples/swat-s1` successfully (loads mininet).
- [ ] perhaps a simple command of the example maybe given to ensure that the system works.

;; minicps dev

- [ ] requirements-dev.txt installs almost everything apart from nose for some reason. Screenshot below.
- [ ] so make tests fails // installed python-nose (maybe the package name has changed?, I am not sure.)

minicps-dev

;; Protocol Wording

- [ ] Under Protocols >  If you want to add a new protocol please look at the minicps/protocols.py module. Protocol is the base class, and the [NewProtocolName]Protocol(Protocol) // added [] around class name
- [ ] Under Testing > Please if you find any inconsistent unit test or decomposable unit test or you want to add a new one. // something's missing. Maybe a pull request statement.

Thank you!

**Comment by francozappa** [comment]
* Re-test 1.1.3 `nose` deps
* Add note about `nosetests` in the user and root `PATH`

**Pull request merged**
